const strings = {
  az: {
    language: 'Azərbaycan dili',
    week_days: ['Bazar', 'Bazar ertəsi', 'Çərşənbə axşamı', 'Çərşənbə', 'Cümə axşamı', 'Cümə', 'Şənbə'],
    months: ['Yanvar', 'Fevral', 'Mart', 'Aprel', 'May', 'İyun', 'İyul', 'Avqust', 'Sentrabr', 'Oktyabr', 'Noyabr', 'Dekabr'],
    home: 'Gündəlik siyahı',
    todolist: 'Ümumi siyahı',
    add_todo: 'Yeni iş əlavə et',
    settings: 'Sazlamalar',
    language_selection: 'Dil seçimi',
    about: 'Müəllif haqqında',
    todos: 'Görülməli işlər',
    notodo_this_day: 'Bu gün üçün görülməli iş əlavə edilməyib',
    confirm_deleting: 'Silinmə əməliyyatını təsdiq edin',
    delete_are_you_sure: 'Silmək istədiyinizə əminsiniz?',
    yes: 'Bəli',
    no: 'Xeyr',
    choose_filter: 'Filtr seçin',
    show_all: 'Hamısını göstər',
    show_completed: 'Yerinə yetirilmişlər',
    show_active: 'Yerinə yetirilməyənlər',
    show_more: 'Daha çox göstər',
    list: 'Siyahı',
    empty_result: 'Filtr üzrə heçnə tapılmadı',
    title: 'Başlıq',
    date: 'Tarix',
    day_of_week: 'Gün',
    choose_day_of_week: 'Gün seçin',
    add: 'Əlavə et',
    todo_added: 'Görüləcək iş müvəffəqiyyətlə əlavə olundu!',
    summary: 'cəmi',
    set_password: 'Şifrə təyin et',
    unset_password: 'Şifrənin sil',
    change_password: 'Şifrəni dəyişmək',
    new_password: 'Yeni şifrə',
    your_password: 'Şifrəniz',
    repeat_password: 'Şifrənin təkrarı',
    password_added_success: 'Şifrə uğurla təyin olundu!',
    password_unset_success: 'Şifrə uğurla silindi!',
    password_added_fail: 'Xəta! Şifrə çox qısadır və yaxud şifrələr uyğun gəlmir.',
    invalid_password: 'Şifrə düzgün daxil edilməyib!',
    valid_password: 'Şifrə düzgün daxil edilib!',
    login_blocked: 'Giriş etmək üçün şifrənizi daxil edin.',
    login: 'Daxil ol'
  },
  en: {
    language: 'English',
    week_days: ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
    home: 'Daily list',
    todolist: 'Full list',
    add_todo: 'Add new todo',
    settings: 'Settings',
    about: 'About author',
    language_selection: 'Language selection',
    todos: 'Works to do',
    notodo_this_day: 'Nothing is added for this day',
    confirm_deleting: 'Delete confirmation',
    delete_are_you_sure: 'Are you sure you want to delete this record?',
    yes: 'Yes',
    no: 'No',
    choose_filter: 'Choose filter',
    show_all: 'Show all',
    show_completed: 'Show completed',
    show_active: 'Show active',
    show_more: 'Show more',
    list: 'List',
    empty_result: 'Nothing was found',
    title: 'Title',
    date: 'Date',
    add: 'Add todo',
    todo_added: 'Todo was added successfully',
    summary: 'total',
    set_password: 'Set password',
    unset_password: 'Unset password',
    change_password: 'Change password',
    new_password: 'New password',
    your_password: 'Your password',
    repeat_password: 'Repeat password',
    invalid_password: 'Incorrect password!',
    valid_password: 'Correct password!',
    password_added_success: 'Password was set successfully!',
    password_unset_success: 'Password was unset successfully!',
    password_added_fail: 'Error! Either password is too short or passwords are not same.',
    login_blocked: 'Enter password in order to countinue.',
    login: 'Login'
  },
  ru: {
    language: 'Русский язык',
    week_days: ['Воскресенье', 'Понедельник', 'Вторник', 'Среда', 'Четверг', 'Пятница', 'Суббота'],
    months: ['января', 'февраля', 'марта', 'апреля', 'мая', 'июня', 'июля', 'августа', 'сентября', 'октября', 'ноября', 'декабря'],
    home: 'Ежедневный список',
    todolist: 'Полный список',
    add_todo: 'Добавление задачи',
    settings: 'Настройки',
    about: 'Об авторе',
    language_selection: 'Выбор языка',
    todos: 'Задачи',
    notodo_this_day: 'На этот день ничего',
    confirm_deleting: 'Подтверждение удаления',
    delete_are_you_sure: 'Вы уверены, что хотите удалить эту запись?',
    yes: 'Да',
    no: 'Нет',
    choose_filter: 'Выберите фильтр',
    show_all: 'Показать все',
    show_completed: 'Выполненные',
    show_active: 'Невыполненные',
    show_more: 'Показать ещё',
    list: 'Список',
    empty_result: 'По фильтру ничего не найдено',
    title: 'Заголовок',
    date: 'Дата',
    add: 'Добавить задачу',
    todo_added: 'Задача успешно добавлена',
    summary: 'всего',
    set_password: 'Установить пароль',
    unset_password: 'Удалить пароль',
    change_password: 'Изменить пароль',
    new_password: 'Новый пароль',
    repeat_password: 'Подтверждение пароля',
    your_password: 'Ваш пароль',
    invalid_password: 'Неверный пароль!',
    valid_password: 'Верный пароль!',
    password_added_success: 'Пароль успешно установлен!',
    password_unset_success: 'Пароль успешно удален!',
    password_added_fail: 'Ошибка! Пароль либо очень короткий либо пароли не совпадают.',
    login_blocked: 'Вход заблокирован. Введите пароль, чтобы продолжить',
    login: 'Войти'
  }
}

export default strings;
